### ISSUE TITLE
The system requirements are not satisfied

### ISSUE THREAD

**Issue by aaqeel87** [intel/haxm#385]
I got a sudden issue with VT-x enables VMs on my VMWare saying not supported on this processor. 
when tried to uninstall and reinstall I got this message in %temp% log file

---------------------------------------
Version: 7.6.5
Execute: C:\Program Files\Intel\HAXM\checktool.exe --verbose
CPU vendor          *  GenuineIntel
Intel64 supported   *  Yes
VMX supported       -  No
VMX enabled         -  No
EPT supported       -  No
NX supported        *  Yes
NX enabled          *  Yes
Hyper-V disabled    -  No
OS version          *  Windows 10.0.19042
OS architecture     *  x86_64
Guest unoccupied    *  Yes. 0 guest(s)
The system requirements are not satisfied.
----------------------------------
p.s tried to install the latest got the same error.

**Comment by wcwang** [comment]
Thanks for your question. Could you check your Hyper-V status first? This [wiki page](https://github.com/intel/haxm/wiki/Windows-Installation-Environment-Check-and-Configurations) may help you to resolve installation issues.

**Comment by aaqeel87** [comment]
@wcwang thanks for reply. Hyper-v is disabled. Is the *.sys file suppose to boot with the OS?

**Comment by wcwang** [comment]
That's true. The HAXM service will start with the host OS. Could you check the feature of Windows Sandbox status further? It has to be disabled too.

**Comment by ickybodclay** [comment]
Having the same issue!  Hyper-v is disabled, Virtualization is enabled in BIOS.  I had it working and noticed there was a new HAXM so I updated and now it's not working.  I did full uninstall and cleanup of old HAXM files and folders, but still having this issue.

Version: 7.7.0
CPU vendor          *  GenuineIntel
Intel64 supported   *  Yes
VMX supported       -  No
VMX enabled         -  No
EPT supported       -  No
NX supported        *  Yes
NX enabled          *  Yes
Hyper-V disabled    -  No
OS version          *  Windows 10.0.19043
OS architecture     *  x86_64
Guest unoccupied    *  Yes. 0 guest(s)

**Comment by wcwang** [comment]
Thanks for your question. Could you check your Hyper-V status first? This [wiki page](https://github.com/intel/haxm/wiki/Windows-Installation-Environment-Check-and-Configurations) may help you to resolve installation issues.

**Comment by aaqeel87** [comment]
> That's true. The HAXM service will start with the host OS. Could you check the feature of Windows Sandbox status further? It has to be disabled too.

Tried it, didn't work.

**Comment by wcwang** [comment]
@aaqeel87, I noticed that your CPU does not support EPT. HAXM can only be installed on the CPU that supports EPT. You may refer to the [specification](https://ark.intel.com) of your CPU model further. Thanks.

**Comment by aaqeel87** [comment]
@wcwang it's been working fine for a year or so! not sure what happened, could be windows update. Either way I had to restore windows just to get rid of it. Thanks for keeping up with us.

**Comment by rosghub** [comment]
@wcwang getting same issue, new Thinkpad X1 with 1135G7 which supports EPT according to Intel spec

**Comment by wcwang** [comment]
@rosghub, thanks for your report. Could you find the installation log in %TEMP% folder first and check your system environment according to the [wiki page](https://github.com/intel/haxm/wiki/Windows-Installation-Environment-Check-and-Configurations)?

**Comment by rosghub** [comment]
@wcwang my issue was resolved by executing the `bcdedit` command for the Hyper-V check. The install completed successfully after rebooting.

This was my complete log in case it helps anyone else:

> Output folder: C:\Program Files\Intel\HAXM
> Extract: checktool.exe
> Execute: C:\Program Files\Intel\HAXM\checktool.exe --verbose
> CPU vendor          *  GenuineIntel
> Intel64 supported   *  Yes
> VMX supported       -  No
> VMX enabled         -  No
> EPT supported       -  No
> NX supported        *  Yes
> NX enabled          *  Yes
> Hyper-V disabled    -  No
> OS version          *  Windows 10.0.19042
> OS architecture     *  x86_64
> Guest unoccupied    *  Yes. 0 guest(s)
> Execute: cmd.exe /c type
>

**Comment by wcwang** [comment]
Thanks for your reply. Hyper-V cannot be re-enabled even after installing HAXM. HAXM cannot coexist with Hyper-V or WSL.

**Comment by KygekDev** [comment]
> Having the same issue! Hyper-v is disabled, Virtualization is enabled in BIOS. I had it working and noticed there was a new HAXM so I updated and now it's not working. I did full uninstall and cleanup of old HAXM files and folders, but still having this issue.
> 
> Version: 7.7.0
> CPU vendor * GenuineIntel
> Intel64 supported * Yes
> VMX supported - No
> VMX enabled - No
> EPT supported - No
> NX supported * Yes
> NX enabled * Yes
> Hyper-V disabled - No
> OS version * Windows 10.0.19043
> OS architecture * x86_64
> Guest unoccupied * Yes. 0 guest(s)

I'm facing the same issue. I'm using Intel NUC8i5BEH with virtualization enabled in BIOS. I also have disabled Hyper-V, WIndows Hypervisor Platform and Windows Sandbox. However, I have WSL and VMware installed, but after checking, it seems like I have WSL version 1, not version 2.

**Comment by wayne-ma** [comment]
> > Having the same issue! Hyper-v is disabled, Virtualization is enabled in BIOS. I had it working and noticed there was a new HAXM so I updated and now it's not working. I did full uninstall and cleanup of old HAXM files and folders, but still having this issue.
> > Version: 7.7.0
> > CPU vendor * GenuineIntel
> > Intel64 supported * Yes
> > VMX supported - No
> > VMX enabled - No
> > EPT supported - No
> > NX supported * Yes
> > NX enabled * Yes
> > Hyper-V disabled - No
> > OS version * Windows 10.0.19043
> > OS architecture * x86_64
> > Guest unoccupied * Yes. 0 guest(s)
> 
> I'm facing the same issue. I'm using Intel NUC8i5BEH with virtualization enabled in BIOS. I also have disabled Hyper-V, WIndows Hypervisor Platform and Windows Sandbox. However, I have WSL and VMware installed, but after checking, it seems like I have WSL version 1, not version 2.

@KygekDev ,please try to disable hyper-V by 'bcedit /set hypervisorlaunchtype off' in terminal with admin account, then reboot your NUC and try again.

**Comment by KygekDev** [comment]
@wayne-ma Tried that and it didn't solve the issue (still giving the same error and output).

**Comment by KygekDev** [comment]
I managed to solve the issue by disabling Secure Boot on the BIOS and setting 'Turn on Virtualization Based Security' on gpedit -> Computer Configuration -> Administrative Templates -> System -> Device Guard to Disabled.

Please let me know if it solves your issue too.

**Comment by pro-munachi** [comment]
> 

I turned on the virtualization and it is not still working

**Comment by wayne-ma** [comment]
> After i installed windows 11, i got an error saying that HAXM installation failed in android studio.

I tried that HAXM works with Windows11. Could you open a new ticket for your issue? Seems it is difference with this one. Appreciate if you could provide more details.
BTW, please also double check if you enabled VT in BIOS and disabled Hyper-V.

**Comment by wayne-ma** [comment]
> > 
> 
> I turned on the virtualization and it is not still working

Please double check if you disabled HyperV. Could you open a new ticket for your issue? Seems it is difference with this one. Appreciate if you could provide more details.

**Comment by letsdoit-jpg** [comment]
some fox said that you should turn off core isolation in your windows 11 settings. and try. but it did not work for me. also u have install wsl2 going on windows PowerShell type -> wsl  --install. let install successfully. it did not work for me but it works for most of people.

**Comment by letsdoit-jpg** [comment]
![image](https://user-images.githubusercontent.com/72949740/147887337-98c3972b-f3b8-411d-9ae5-1ba3be7db55d.png)
I figured out my issues. make sure your windows features looks like this. turn off your core isolations. try it it does not work install wsl  --install in PowerShell. it will work.
